### ISSUE TITLE
Upgrade to elm 0.19

### ISSUE THREAD

**Issue by arian** [michie1/wrs_elm#20]
Would be a fun exercise to do.

- http://elm-lang.org/blog/small-assets-without-the-headache
- https://korban.net/posts/elm/2018-08-22-elm-019-whats-new-install-upgrade/

**Comment by michie1** [comment]
At the end of the year I'm planning to download all data and store it in a json file, than I'll put the data and the dist on a separate subdomain. In December I'll update to 0.19, so in 2019 we start with a new version and a fresh database.

**Comment by michie1** [comment]
I'll probably wait for 0.20 to update, because 0.18 is running stable and there is nearly no development.

**Comment by michie1** [comment]
@arian "a fun exercise" :poop:
