### ISSUE TITLE
Points per year

### ISSUE THREAD

**Issue by michie1** [michie1/wrs_elm#5]
Op de detail pagina van een renner kan je nu zien hoeveel punten een renner gehaald heeft. Voor nu is dat voldoende, maar in de toekomst wil je eigenlijk zien hoeveel punten iemand heeft voor het huidige jaar. Daarnaast zou je eigenlijk ook de tabel met uitslagen van deze renners willen opdelen per jaar en dat je per jaar ziet hoeveel punten er behaald is.

**Comment by waikontse** [comment]
Kan je deze ticket  beter beschrijven ? Misschien doe ik ook deze ticket in mijn vrije tijd.

**Comment by michie1** [comment]
Ik zal in het vervolg er rekening mee houden dat ik niet de enige ben die het leest. ;-) Ik heb een beschrijving toegevoegd.

**Comment by michie1** [comment]
`Daarnaast zou je eigenlijk ook de tabel met uitslagen van deze renners willen opdelen per jaar en dat je per jaar ziet hoeveel punten er behaald is.` Dit idee is verlopig weg, aangezien 2018 read only is uit json files en niet meer via firebase.
