### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by arian** [michie1/wrs_elm#8]
Ik reageer hier maar even, wat meer ruimte :smile: 

Over het algemeen ziet het er wel goed uit volgens mij... 
Paar dingetjes die mij opvielen:

---

```elm
type alias App =
    { page : Page
    , riders : Maybe (List Rider)
    , races : Maybe (List Race)
    , results : Maybe (List RaceResult)
    }
```

De `Maybe (List Rider)` ziet er een beetje raar uit... maar op zich wel logisch uiteindelijk :thinking: 

---

Ik zou de verschillende elementen/pages die je hebt iets meer los trekken en later 'composen'.

Dus eigenlijk wat je met `Page.Race.Add` gedaan hebt.

Door middel van `Html.map` oid kun je de locale `Msg` type mappen naar de gebruiker van de locale `view` en `update` functies.

Dan hoef je ook niet overal `view : a -> Html App.Msg.Msg` te hebben. Dan heb je wel een erg losse koppeling tussen je App Msg type en de specifieke views. Nu is je `Msg` type nog niet heel erg lang, maar anders wordt het refactoren lastig denk ik, omdat de Msg dan erg ver bij elkaar vandaan staan.

---

Eventueel kun je de locale `update` functie een tuple laten returnen met een `ExternalMsg` om aan de bovenliggende update function te laten weten dat iets gebeurd is:

https://github.com/rtfeldman/elm-spa-example/blob/74cb1e5da06492050ed4cf3002c3eef2d2ca184d/src/Page/Settings.elm#L122-L208

---

Over `Page.Race.Add` gesproken... Ik zou die Model, Update, Msg en View modules gewoon in 1 module zetten:

1. Anders krijg je 10tallen Update.elm modules
2. Het hoort bij elkaar, dus waarom niet bij elkaar zetten.
3. Je kunt de `App.Msg` 'private' houden... dat niet willekeurige elementen/views een Msg kunnen dispatchen (wat nu wel kan, bijvoorbeeld je `Page.Result.List.view` function).

---

Die jquery en materialize js files in je GIT source control :sweat_smile:

**Comment by arian** [comment]
En uiteindelijk gaat natuurlijk nooit alle data uit de database in je model passen... of, dat zal niet practisch zijn...

**Comment by michie1** [comment]
Bedankt voor je feedback! Ik reageer even per onderdeel.

**Comment by michie1** [comment]
> De Maybe (List Rider) ziet er een beetje raar uit... maar op zich wel logisch uiteindelijk :thinking:
Het is sowieso beter dan een lege List. Als er een request werd gedaan vanuit Elm zou ik er een Result van hebben gemaakt, maar opzich is dit wel een eenvoudige oplossing.

**Comment by michie1** [comment]
> Ik zou de verschillende elementen/pages die je hebt iets meer los trekken en later 'composen'.
> Dus eigenlijk wat je met Page.Race.Add gedaan hebt.
> 
> Door middel van Html.map oid kun je de locale Msg type mappen naar de gebruiker van de locale view en update functies.
> 
> Dan hoef je ook niet overal view : a -> Html App.Msg.Msg te hebben. Dan heb je wel een erg losse koppeling tussen je App Msg type en de specifieke views. Nu is je Msg type nog niet heel erg lang, maar anders wordt het refactoren lastig denk ik, omdat de Msg dan erg ver bij elkaar vandaan staan.

Volgens mij heb ik dat nu voor elke Page gedaan. "Did you pull latest?" Nog niet zo lang geleden had ik alles in één `Msg` en in de update functie callde ik dan weer een subupdate functie uit een ander bestand. Mijn strategie was om het een ander keertje uit te zoeken hoe je iets netjes opdeelt.

**Comment by michie1** [comment]
> Eventueel kun je de locale update functie een tuple laten returnen met een ExternalMsg om aan de bovenliggende update function te laten weten dat iets gebeurd is:

> https://github.com/rtfeldman/elm-spa-example/blob/74cb1e5da06492050ed4cf3002c3eef2d2ca184d/src/Page/Settings.elm#L122-L208

Tot nu toe zijn er nog geen Pages die een App.Msg willen sturen, ze sturen enkel hun eigen SubMsg (die dan in de App.Update weer gemapt wordt naar een Msg).

**Comment by michie1** [comment]
> Over Page.Race.Add gesproken... Ik zou die Model, Update, Msg en View modules gewoon in 1 module zetten:

> 1. Anders krijg je 10tallen Update.elm modules
> 2. Het hoort bij elkaar, dus waarom niet bij elkaar zetten.
> 3. Je kunt de App.Msg 'private' houden... dat niet willekeurige elementen/views een Msg kunnen dispatchen (wat nu wel kan, bijvoorbeeld je Page.Result.List.view function).

1. Wat is daar het nadeel van?
2. Ik vind het nu handig als ik naar een Page.View bestand ga, dat ik direct bij de View code ben. Als je alles in één bestand zet, dan moet je er alsnog naar navigeren. 
3. Opzich wel goed punt. (Alhoewel het wel handig is als `App.Msg` een eigen bestand heeft, als de `ExternalMsg` van je vorige comment precies `App.Msg` is.)

**Comment by michie1** [comment]
> Die jquery en materialize js files in je GIT source control :sweat_smile:
In plaats van netjes opbergen wil ik die op termijn deprecaten. Heb daar nog 0 aandacht aan besteed. Terechte opmerking.

**Comment by michie1** [comment]
> En uiteindelijk gaat natuurlijk nooit alle data uit de database in je model passen... of, dat zal niet practisch zijn...

Eens. 'k schat dat ik er naar ga kijken als we tegen de 200 resultaten zitten.

**Comment by michie1** [comment]
Nog iets van features die je mist voordat het in gebruik kan?

**Comment by arian** [comment]
> Opzich wel goed punt. (Alhoewel het wel handig is als App.Msg een eigen bestand heeft, als de ExternalMsg van je vorige comment precies App.Msg is.)

Niet helemaal...

`App.Msg` is iets wat van je `view` functies komt.

`ExternalMsg` is iets wat je locale update functie als extra return waarde terug geeft aan de bovenliggende update functie.

```elm
myPageUpdate : PageMsg PageModel -> (PageModel, ExternalMsg)
myPageUpdate msg model = ...
```

**Comment by arian** [comment]
> Het is sowieso beter dan een lege List. Als er een request werd gedaan vanuit Elm zou ik er een Result van hebben gemaakt, maar opzich is dit wel een eenvoudige oplossing.

Een result in je Model is wel een beetje gek... Ik denk dat het nu goed is: Of er mist wat, of er is een lijst (al dan niet leeg)... Al kan een result natuurlijk ook een error hebben... Het punt is, is dat je dit een beetje aan de 'rand' van je applicatie wilt houden... 'intern' wil je gewoon de lijst met renners of wedstrijden... :thinking:

**Comment by michie1** [comment]
Betreft `ExternalMsg` kan je een meer specifiek voorbeeld geven hoe je het anders wil zien?

**Comment by michie1** [comment]
> Een result in je Model is wel een beetje gek... Ik denk dat het nu goed is: Of er mist wat, of er is een lijst (al dan niet leeg)... Al kan een result natuurlijk ook een error hebben... Het punt is, is dat je dit een beetje aan de 'rand' van je applicatie wilt houden... 'intern' wil je gewoon de lijst met renners of wedstrijden... :thinking:

Het laden zou verkeerd kunnen gaan en dat zou een error (van Result) wel netjes zijn. In de `mainView` zijn overigs `races`, `riders` en `results` beschikbaar zonder de `Maybe`.

**Comment by michie1** [comment]
Ik probeer de `Msg`, `Model`, `Update`, `View` bestanden te mergen, maar krijg helaas een circular dependency error. 
>  ┌─────┐
>  │    App.Model
>  │     ↓
>  │    App.Page
>  │     ↓
>  │    Page.Race.Add
>  └─────┘

**Comment by michie1** [comment]
Ik lees hier https://github.com/rtfeldman/elm-spa-example/blob/74cb1e5da06492050ed4cf3002c3eef2d2ca184d/src/Main.elm#L25 dat er in 0.19 hoop gaat veranderen waardoor er minder nodig is. Daar ga ik dus op wachten.
